apiVersion: v1
data:
  config.json: '{"sink":"stdout","namespace":"{{ .Release.Namespace | default "default" }}","lastResourceVersionPositionPath":"/var/pos/event-tailer"}'
kind: ConfigMap
metadata:
  name: {{ include "eventrouter.fullname" . }}
