apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eventrouter.fullname" . }}
rules:
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - watch
  - list
